### ISSUE TITLE
Shortcut not working

### ISSUE THREAD

**Issue by Lucandia** [adriangalilea/streamlit-shortcuts#15]
Hi, 
I'm trying to use the keyboard shortcut with the last version of streamlit (Streamlit nightly), and I can't make it work, I'm trying both on Safari and Firefox.

I tried running the example
```
import streamlit as st
import streamlit_shortcuts

def delete_callback():
    st.write("DELETED!")

streamlit_shortcuts.button("delete", on_click=delete_callback, shortcut="Ctrl+Shift+X", hint=True)
```
It works fine if I press the button, but the shortcut doesn't work.

Also, if I add any args like this:
```
def delete_callback(text):
 st.write(f"DELETED {text}!")

streamlit_shortcuts.button("delete", on_click=delete_callback, shortcut="Ctrl+Shift+X", hint=True, args=("text",))
```

I get this error:
```
Traceback (most recent call last):
 File "/Users/lmonari/anaconda3/envs/roadgui/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
 result = func()
 File "/Users/lmonari/anaconda3/envs/roadgui/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
 exec(code, module.__dict__)
 File "/Users/lmonari/Documents/software/pyFuRNAce/test_shortcut.py", line 7, in <module>
 streamlit_shortcuts.button("delete", on_click=delete_callback, shortcut="Ctrl+Shift+X", hint=True, args=("text",))
 File "/Users/lmonari/anaconda3/envs/roadgui/lib/python3.9/site-packages/streamlit_shortcuts/streamlit_shortcuts.py", line 74, in button
 return st.button(
TypeError: streamlit.delta_generator.ButtonMixin.button() got multiple values for keyword argument 'args'
```

**Comment by adriangalilea** [comment]
Hey @Lucandia 

Thanks for filling the issue,

Have you tried with the regular version of streamlit?

**Comment by Lucandia** [comment]
I have the same errors and problems with the regular version of streamlit (streamlit==1.38.0)

**Comment by adriangalilea** [comment]
Have  you tried the latest streamlit-shortcuts version I just released? @Lucandia

**Comment by Lucandia** [comment]
Oh, I missed it. It works like a charm now, thank you so much!
